### ISSUE TITLE
Code review 19/04

### ISSUE THREAD

**Issue by KaanKalmi** [SamaraFellaDina/user-experience-enhanced-website#9]
### EJS
Ik heb overall niet veel gevonden dat opmerkelijk is aan jouw code, Ik zie wel dat je vaker een `<h1>` gebruikt is dit handig volgens jou? Kijk eens naar [W3 headings accessibility](https://www.w3.org/WAI/tutorials/page-structure/headings/)!

Ook zie ik een home.ejs en een article.ejs maar geen index.ejs, ik weet niet of je de server.js zo hebt opgesteld dat de ingeladen EJS een ander naam kan hebben dan index.ejs als het zo is lemme know das namelijk best geinig om te weten en mee te spelen!

Als laatst zie ik wel dat je 2 verschillende ejs bestanden hebt met min of meer hetzelfde code (je article.ejs en home.ejs), kan je hier niet 1 bestand van maken?

_Je hebt in je head.ejs een `<header>` met een `<div>` erin de div kan in principe gewoon een `<nav>` worden!_
### CSS
Niet echt iets opgevallen aan je CSS, je kan alleen wel kijken naar [CSS Nesting](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting), en het minifyen van sommige lines:
```css
h1,
h2,
h3,
h4,
h5,
h6 {
    font-family: var(--font-serif);
    font-weight: 900;
}
```
Dit zou je kunnen veranderen naar:
```css
h1, h2, h3, h4, h5, h6 {
    font-family: var(--font-serif);
    font-weight: 900;
}
```

Hierdoor heb je minder CSS lines en is je CSS bestand dus ook kleiner (bespaart inlaad tijd als je grote CSS bestanden inlaad!)

### Server.js
Netjes opgebouwd, het is structured en organised ook heb je nog comments erbij voor elk gegroepeerd stukje.
